apiVersion: v1
kind: Config
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:6443
  name: rusternetes
contexts:
- context:
    cluster: rusternetes
    user: admin
  name: rusternetes
current-context: rusternetes
users:
- name: admin
  user: {}
