pub mod annotate;
pub mod api_resources;
pub mod api_versions;
pub mod apply;
pub mod attach;
pub mod auth;
pub mod autoscale;
pub mod certificate;
pub mod cluster_info;
pub mod completion;
pub mod config;
pub mod cp;
pub mod create;
pub mod debug;
pub mod delete;
pub mod describe;
pub mod diff;
pub mod drain;
pub mod edit;
pub mod events;
pub mod exec;
pub mod explain;
pub mod expose;
pub mod get;
pub mod help;
pub mod kuberc;
pub mod kustomize;
pub mod label;
pub mod logs;
pub mod options;
pub mod patch;
pub mod plugin;
pub mod port_forward;
pub mod proxy;
pub mod replace;
pub mod rollout;
pub mod run;
pub mod scale;
pub mod set;
pub mod taint;
pub mod top;
pub mod version;
pub mod wait;

#[cfg(test)]
mod apply_test;
#[cfg(test)]
mod create_test;
#[cfg(test)]
mod get_test;
