#!/bin/bash

# Generate Default ServiceAccounts and Tokens
# This script generates unique ServiceAccount tokens for default namespaces
# These tokens are NOT committed to git for security reasons

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

print_step() {
    echo -e "${GREEN}==>${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}WARNING:${NC} $1"
}

# Generate a random JWT-style token (for development purposes only)
# In production, these would be properly signed JWTs
generate_token() {
    local namespace=$1
    # Generate a random base64-encoded string (64 bytes = good entropy)
    openssl rand -base64 64 | tr -d '\n'
}

# Create ServiceAccount and Secret YAML for a namespace
create_sa_resources() {
    local namespace=$1
    local token=$(generate_token "$namespace")
    local token_b64=$(echo -n "$token" | base64)
    local namespace_b64=$(echo -n "$namespace" | base64)

    cat << EOF
---
# Default ServiceAccount for $namespace namespace
# Generated by scripts/generate-default-serviceaccounts.sh
# NOTE: In production Kubernetes, ServiceAccounts and tokens are created automatically
# by the ServiceAccount controller and TokenController.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: $namespace
---
# Default ServiceAccount token for $namespace namespace
# WARNING: This is a development token, not a properly signed JWT!
# For testing purposes only.
apiVersion: v1
kind: Secret
metadata:
  name: default-token
  namespace: $namespace
  annotations:
    kubernetes.io/service-account.name: default
type: kubernetes.io/service-account-token
data:
  token: $token_b64
  namespace: $namespace_b64
EOF
}

# Main script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="${SCRIPT_DIR}/.rusternetes/default-serviceaccounts.yaml"

print_step "Generating default ServiceAccounts and tokens..."

# Create .rusternetes directory if it doesn't exist
mkdir -p "${SCRIPT_DIR}/.rusternetes"

# Generate the YAML file
{
    echo "# Default ServiceAccounts and Tokens"
    echo "# Generated by scripts/generate-default-serviceaccounts.sh"
    echo "# DO NOT COMMIT THIS FILE - IT CONTAINS GENERATED TOKENS"
    echo "# This file is automatically created during cluster bootstrap"
    echo ""
    create_sa_resources "default"
    create_sa_resources "kube-system"
} > "$OUTPUT_FILE"

print_step "Generated ServiceAccounts saved to: $OUTPUT_FILE"
echo ""
print_warning "This file contains generated tokens and should NOT be committed to git!"
print_warning "It is automatically created during bootstrap and is .gitignored"
echo ""
echo "To apply these resources:"
echo "  export KUBECONFIG=.rusternetes/kubeconfig"
echo "  ./target/release/kubectl apply -f $OUTPUT_FILE"
echo ""
